version: '3.4'

services:
  pci-backend-prod:
    container_name: pci-backend-prod
    image: piwatcher/pci-backend:1.0.0
    restart: unless-stopped
    environment:
      APP_ENV: Production 
      MONGO_USER: "${MONGO_USER}"
      MONGO_PASS: "${MONGO_PASS}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      MONGO_HOSTNAME: mongodb-prod
      MONGO_PORT: 27017
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb-prod
    networks:
      - backend_prod

  mongodb-prod:
    image: mongo:4.0.8
    container_name: mongodb-prod
    restart: unless-stopped 
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${ROOT_PASS}"
      MONGODB_DATA_DIR: /data/prod/db
      MONGODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/prod/db
    networks:
      - backend_prod

volumes:
  mongodbdata:
    driver: local

networks:
  backend_prod:
    driver: bridge